### ISSUE TITLE
Plugin with migrations is not working on running `npm run dev`

### ISSUE THREAD

**Issue by y471n** [actionhero/ah-sequelize-plugin#127]
Followed the steps exactly, without sequelize-cli installation. 
npm run dev is working.

Add a migration folder and a migration file, run `npm run dev` it throws error:

```
Compilation error in /Users/ymmy/code/oss/actionhero/bl1/src/config/sequelize.js
Error: extHandler is not a function
    at Object.<anonymous> (/Users/ymmy/code/oss/actionhero/bl1/src/config/sequelize.js:1:7)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (/Users/ymmy/code/oss/actionhero/bl1/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/rl/hjlnn6ld1xd2s5p8kvv4ffvm0000gn/T/ts-node-dev-hook-9040239641742598.js:93:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at require.extensions..js (/private/var/folders/rl/hjlnn6ld1xd2s5p8kvv4ffvm0000gn/T/ts-node-dev-hook-9040239641742598.js:96:14)
    at Object.nodeDevHook [as .js] (/Users/ymmy/code/oss/actionhero/bl1/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
```

**Comment by evantahler** [comment]
The quick solution would be to add `"allowJs": true` in your `tsconfig.json`, but the long-term solution is https://github.com/actionhero/ah-sequelize-plugin/pull/128
