### ISSUE TITLE
SequelizeConnectionError: password authentication failed for user "LenovoPC"

### ISSUE THREAD

**Issue by krlicmuhamed** [actionhero/ah-sequelize-plugin#152]
So I get this error while trying to run a project based on `actionhero-chat` project that is now archived. 
Here's my config file (notice I don't have a password for my localhost postgres)
```
{
  "development": {
    "username": "postgres",
    "password": null,
    "database": "anyplace",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "test": {
    "username": "postgres",
    "password": null,
    "database": "anyplace",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "production": {
    "username": "postgres",
    "password": null,
    "database": "anyplace",
    "host": "127.0.0.1",
    "dialect": "postgres"
  }
}
```
Yet I still get password auth failure:
```
LenovoPC@laptop MINGW64 /c/Projects/AnyPlaceOld/api/src
$ npm run dev
> anyplace@0.1.0 dev C:\Projects\AnyPlaceOld
> cd api && ts-node-dev --transpile-only --ignore-watch="../web" --no-deps --notify=false ./src/server.ts
Using ts-node version 8.10.2, typescript version 3.8.3
emerg: Exception occurred in initializer `sequelize` during load 
emerg: Error with initializer step: "initialize" 
emerg: SequelizeConnectionError: password authentication failed for user "LenovoPC"
   at C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:182:24
   at Connection.connectingErrorHandler (C:\Projects\AnyPlaceOld\node_modules\pg\lib\client.js:203:14)
   at Connection.emit (events.js:315:20)
   at Socket.<anonymous> (C:\Projects\AnyPlaceOld\node_modules\pg\lib\connection.js:120:12)
   at Socket.emit (events.js:315:20)
   at addChunk (_stream_readable.js:295:12)
   at readableAddChunk (_stream_readable.js:271:9)
   at Socket.Readable.push (_stream_readable.js:212:10)
   at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
From previous event:
   at ConnectionManager.connect (C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:121:12)
   at C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:318:50
   at processImmediate (internal/timers.js:456:21)
From previous event:
   at ConnectionManager._connect (C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:318:8)
   at ConnectionManager.getConnection (C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:254:46)
   at C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\sequelize.js:640:36
From previous event:
   at C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\sequelize.js:631:53
   at C:\Projects\AnyPlaceOld\node_modules\retry-as-promised\index.js:70:21
at new Promise (<anonymous>)
   at retryAsPromised (C:\Projects\AnyPlaceOld\node_modules\retry-as-promised\index.js:60:10)
   at C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\sequelize.js:631:30
From previous event:
   at Sequelize.query (C:\Projects\AnyPlaceOld\node_modules\sequelize\lib\sequelize.js:580:23)
   at SequelizeInitializer.test (C:\Projects\AnyPlaceOld\node_modules\ah-sequelize-plugin\dist\initializers\sequelize.js:77:42)
   at SequelizeInitializer.initialize (C:\Projects\AnyPlaceOld\node_modules\ah-sequelize-plugin\dist\initializers\sequelize.js:18:20
   at Object.initializeFunction (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\classes\process.js:97:47)
   at Object.asyncWaterfall (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\modules\utils\asyncWaterfall.js:46:33)
   at processTicksAndRejections (internal/process/task_queues.js:97:5)
   at Process.initialize (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\classes\process.js:166:13)
   at Process.start (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\classes\process.js:176:13)
   at main (C:\Projects\AnyPlaceOld\api\src\server.ts:16:3)
crit: Cannot shut down actionhero, not running
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anyplace@0.1.0 dev: `cd api && ts-node-dev --transpile-only --ignore-watch="../web" --no-deps --notify=false ./src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anyplace@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LenovoPC\AppData\Roaming\npm-cache\_logs\2020-07-17T19_52_25_799Z-debug.log
```

**Comment by evantahler** [comment]
It looks like none of your config options are making it to the pg connection - the username, password, etc.  What version of `ah-sequelize-plugin` are you using, and can you share your whole `src/config/sequelize.ts`?

**Comment by krlicmuhamed** [comment]
Here goes the orm version `Sequelize CLI [Node: 12.18.0, CLI: 6.2.0, ORM: 5.21.6]`
And this is the file from `src/config/sequelize.ts`
```
import { URL } from "url";
import { join } from "path";

const databaseBaseName = "chat_sample_project";

export const DEFAULT = {
  sequelize: (config) => {
    let dialect = "postgres";
    let host = process.env.DB_HOST || "127.0.0.1";
    let port = process.env.DB_PORT || "5432";
    let database =
      process.env.DB_DATABASE ||
      `${databaseBaseName}_${config.process.env}${
        process.env.JEST_WORKER_ID ? "_" + process.env.JEST_WORKER_ID : ""
      }`;
    let username =
      process.env.DB_USER || process.env.CI ? "postgres" : undefined;
    let password = process.env.DB_PASS || undefined;

    // if your environment provides database information via a single JDBC-style URL like mysql://username:password@hostname:port/default_schema
    const connectionURL =
      process.env.DATABASE_URL || process.env.MYSQL_URL || process.env.PG_URL;

    if (connectionURL) {
      const parsed = new URL(connectionURL);
      if (parsed.protocol) {
        dialect = parsed.protocol.slice(0, -1);
      }
      if (parsed.username) {
        username = parsed.username;
      }
      if (parsed.password) {
        password = parsed.password;
      }
      if (parsed.hostname) {
        host = parsed.hostname;
      }
      if (parsed.port) {
        port = parsed.port;
      }
      if (parsed.pathname) {
        database = parsed.pathname.substring(1);
      }
    }

    if (dialect === "postgresql") {
      dialect = "postgres";
    }

    return {
      autoMigrate: true,
      logging: false,
      dialect: dialect,
      port: parseInt(port),
      database: database,
      host: host,
      username: username,
      password: password,
      models: [join(__dirname, "..", "models")],
      migrations: [join(__dirname, "..", "migrations")],
    };
  },
};
```

**Comment by krlicmuhamed** [comment]
Works If I put in DB_USER env variable behind `DB_USER=postgres npm run dev`. Still dunno why It doesn't read config.json file like it should...
But now I have another error caused by ah-next-plugin
```
notice: pid: 2172 
notice: environment: development 
info: *** Starting Actionhero ***
info: actionhero member 192.168.0.17 has joined the cluster 
emerg: Exception occurred in initializer `next` during start 
emerg: Error with initializer step: "start"
emerg: TypeError: Cannot read property 'dev' of undefined
    at Next.start (C:\Projects\AnyPlaceOld\node_modules\ah-next-plugin\dist\initializers\next.js:32:38)
    at Object.startFunction (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\classes\process.js:119:47)
    at Object.asyncWaterfall (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\modules\utils\asyncWaterfall.js:46:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Process.start (C:\Projects\AnyPlaceOld\node_modules\actionhero\dist\classes\process.js:195:13)
    at main (C:\Projects\AnyPlaceOld\api\src\server.ts:16:3)
notice: stopping process...
notice: Stopping server: web
notice: Stopping server: websocket
notice: *** Actionhero Stopped ***
```

**Comment by mfvargo** [comment]
Here is my simplest of src/config/sequelize.ts files.  I think you need to last 3 lines to export the environments.  That's why it can't find 'dev' cause you don't have one?

my setup uses same username and password and a database called "BASENAME_development" or BASENAME_production etc...

```
const env = process.env.NODE_ENV || "development";
const dbName = "BASENAME_" + env;
const mysqlHost = process.env.MYSQL_HOST || "127.0.0.1";
import * as path from "path";

export const DEFAULT = {
  sequelize: function () {
    return {
      autoMigrate: false,
      loadFixtures: false,
      database: dbName, // From the code above
      dialect: "mysql",
      port: 3306,
      host: mysqlHost,
      username: "USERNAMEGOESHERE",
      password: "PASSWORD_GOES_HERE",
      logging: false,
      models: [path.join(__dirname, "..", "models")],
      migrations: [path.join(__dirname, "..", "migrations")],
    };
  },
};

module.exports.test = DEFAULT.sequelize();
module.exports.development = DEFAULT.sequelize();
module.exports.production = DEFAULT.sequelize();
```

**Comment by evantahler** [comment]
Closing due to lack of response
